apiVersion: v1
kind: Service
metadata:
  name: node-app-svc
  labels:
    app: node-app
spec:
  type: ClusterIP
  ports:
    - port: 6002
      targetPort: 6002
  selector:
    app: node-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: node-app # Assumes you have built an image with this name
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6002
          env:
            # These values point to the Kubernetes Service for the Spring Boot app
            - name: SPRING_SERVICE_HOST
              value: "spring-app-svc"
            - name: SPRING_SERVICE_PORT
              value: "6001"
