apiVersion: v1
kind: Service
metadata:
  name: node-app-svc
  labels:
    app: node-app
spec:
  type: ClusterIP
  ports:
  - port: 6002
    targetPort: 6002
  selector:
    app: node-pub
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-pub-deployment
  labels:
    app: node-pub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-pub
  template:
    metadata:
      labels:
        app: node-pub
      annotations:
        instrumentation.opentelemetry.io/inject: 'true'
        instrumentation.opentelemetry.io/inject-nodejs: 'true'
    spec:
      containers:
      - name: node-app
        image: user-app-node-pub:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 6002
        env:
        - name: SPRING_SERVICE_HOST
          value: spring-app-svc
        - name: SPRING_SERVICE_PORT
          value: '6001'
      serviceAccountName: traceassist-sa
